#!/usr/bin/tcsh

##after Qiime2 is active...

qiime tools import \
--type 'SampleData[SequencesWithQuality]' \
--input-path raw-reads/ \
--input-format CasavaOneEightSingleLanePerSampleDirFmt \
--output-path demux-single-end.qza
##this converts your FASTA files into a qiime-formatted file (.qza)
##after input-path type the folder name where you keep your raw reads
##the format of the reads should be: .fastq.gz file, with each file containing seq and quality (MUST BE GZIPPED)
##each file represents one sample or sequencing lane, either forward (R1) or reverse reads (R2)
##this input format doesn't combine forward and reverse reads, only one direction
##with previous seep work the R2s were bad and made everything garbage, thus, single direction
qiime demux summarize \
--i-data demux-single-end.qza \
--o-visualization demux.qzv
##view by downloading file via CyberDuck and uploading it at https://view.qiime2.org/
##or if you're working in VirtualBox:
# qiime tools view demux.qzv
##this produces a qiime graph that shows you two things:
##1. number of reads in each sample
##2. a graph showing the quality of the read over the sequence
##using 2, you'll want to choose how much on each end to cut off, based on where the ends significantly decrease in quality

qiime dada2 denoise-single \
--i-demultiplexed-seqs demux-single-end.qza \
--p-n-threads 16 \
--p-trim-left 13 \
--p-trunc-len 181 \
--o-representative-sequences unfiltered-rep-seqs.qza \
--o-table unfiltered-table.qza \
--o-denoising-stats unfilter-denoise-stats.qza
##this step is a long one, usually runs 1-3 hours
##it cleans up the sequences, chopping off bad quality ends
## the p-n-threads makes sure qiime uses all processors assigned to it
##again you will set the lengths based on demux results
##first 12 bp are usually adapter so you can keep the p-trim-left the same
qiime metadata tabulate \
--m-input-file unfilter-denoise-stats.qza \
--o-visualization unfilter-denoise-stats.qzv
##view the results of your cleanup using qiime tools view or view.qiime2.org
##at this point it will still include samples with too few reads, so to remove those we will do the following...

qiime feature-table filter-samples \
--i-table unfiltered-table.qza \
--p-min-frequency 6500 \
--o-filtered-table filtered-table.qza
##the p-min-frequency is the minimum number of reads per sample you want to include
##all samples with fewer than that many reads (bad seq reaction?) will be removed
##use demux.qzv to determine a good cut-off for minimum reads
qiime feature-table filter-seqs \
--i-data unfiltered-rep-seqs.qza \
--i-table filtered-table.qza \
--o-filtered-data filtered-rep-seqs.qza
##this will filter out all sequences that are absent from the table
##visualize the results of filtering as follows...
qiime feature-table summarize \
--i-table filtered-table.qza \
--m-sample-metadata-file metadata.tsv \
--o-visualization filtered-table.qzv
qiime feature-table tabulate-seqs \
--i-data filtered-rep-seqs.qza \
--o-visualization filtered-rep-seqs.qzv

##at this point I like to make folders for the unfiltered files, as well as all the visualizations/qzv to get them out of the way

##I generated a classifier based on the Silva database. (trimmed to 515F/806R region)
##see my silva-classifier-creation file for my process.
##using this Silva classifier...
qiime feature-classifier classify-sklearn \
--i-classifier silva-classifier.qza \
--i-reads filtered-rep-seqs.qza \
--p-n-jobs -1 \
--o-classification taxonomy.qza
##this is a long and intense step, 6 hours or more. leave it overnight
##p-n-jobs with -1 ensures that all available processors are used; if you use 1 then only one will be used
qiime metadata tabulate \
--m-input-file taxonomy.qza \
--o-visualization taxonomy.qzv
##this views the results of your taxonomy

##create beautiful and fun graphics of the taxonomy
qiime taxa barplot \
--i-table filtered-table.qza \
--i-taxonomy taxonomy.qza \
--m-metadata-file metadata.tsv \
--o-visualization taxa-bar-plots.qzv
##from the visualization, you can download the taxa barplot images themselves
##AND you can get CSV files of tabulated samples vs. taxonomies at a given taxonomy level (level 4 usually most helpful)

##alpha and beta diversity stats
#first create a phylogenetic tree
qiime phylogeny align-to-tree-mafft-fasttree \
--i-sequences rep-seqs.qza \
--o-alignment aligned-rep-seqs.qza \
--o-masked-alignment masked-aligned-rep-seqs.qza \
--o-tree unrooted-tree.qza \
--o-rooted-tree rooted-tree.qza
#not a super intensive step, so something I can do on my own computer

#then generate diversity core metrics
qiime diversity core-metrics-phylogenetic \
--i-phylogeny rooted-tree.qza \
--i-table filtered-table.qza \
--p-sampling-depth 6500 \
--m-metadata-file metadata.tsv \
--output-dir core_metrics_results
##creates a whole bunch of diversity stats, alpha and beta, and some emperor plots/NMDS
##made the sampling depth the same as above, but since I'm using the filtered table anyway it's a bit redundant!
