#!/usr/bin/tcsh

##after Qiime2 is active...

qiime tools import \
--type 'SampleData[SequencesWithQuality]' \
--input-path raw-reads/ \
--input-format CasavaOneEightSingleLanePerSampleDirFmt \
--output-path demux-single-end.qza
##this converts your FASTA files into a qiime-formatted file (.qza)
##after input-path type the folder name where you keep your raw reads
##the format of the reads should be: .fastq file, with each file containing seq and quality
##each file represents one sample or sequencing lane, either forward (R1) or reverse reads (R2)
##this input format doesn't combine forward and reverse reads, only one direction

##with previous seep work the R2s were bad and made everything garbage, thus, single direction

qiime demux summarize \
--i-data demux-single-end.qza \
--o-visualization demux.qzv
##view by downloading file via CyberDuck and uploading it at https://view.qiime2.org/
##or if you're working in VirtualBox:
#qiime tools view demux.qzv
##this produces a qiime graph that shows you two things:
##1. number of reads in each sample
##2. a graph showing the quality of the read over the sequence
##using 2, you'll want to choose how much on each end to cut off, based on where the ends significantly decrease in quality

qiime dada2 denoise-single \
--i-demultiplexed-seqs demux-single-end.qza \
--p-trim-left 13 \
--p-trunc-len 181 \
--o-representative-sequences unfiltered-rep-seqs.qza \
--o-table unfiltered-table.qza \
--o-denoising-stats unfilter-denoise-stats.qza
##this cleans up the sequences, chopping off bad quality ends
##again you will set the lengths based on demux results
##first 12 bp are usually adapter so you can keep the p-trim-left the same

qiime metadata tabulate \
--m-input-file unfilter-denoise-stats.qza \
--o-visualization unfilter-denoise-stats.qzv
##view the results of your cleanup using qiime tools view or view.qiime2.org
##at this point it will still include samples with too few reads, so to remove those we will do the following...

qiime feature-table filter-samples \
--i-table unfiltered-table.qza \
--p-min-frequency 6500 \
--o-filtered-table table.qza
##the p-min-frequency is the minimum number of reads per sample you want to include
##all samples with fewer than that many reads (bad seq reaction?) will be removed
##use demux.qzv to determine a good cut-off for minimum reads
