#!/usr/bin/tcsh

##once you have a CGRB account, here's how to run Qiime on it!
##my working directory on the CGRB is as follows:
cd /nfs1/MICRO/Thurber_Lab/susie/

qrsh -q micro
#this should connect you to the server microbiome or calculon
#if you want to request a certain number of processors, add "-pe thread #" to the end

conda activate qiime2-2019.7
#this activates a conda environment that allows Qiime to be run

qiime --help
#this allows you to test whether qiime is working. if it gives you a big help dialogue, you're good

#in another window, again connect to the CGRB so you can check your progress/usage
qrsh -q micro@calculon
#this ensures you connect to the same server as above (use "microbiome" if you're on that one)
top
#press q when finished
