#!/usr/bin/tcsh

#import seq files
qiime tools import \
--type 'SampleData[SequencesWithQuality]' \
--input-path raw-reads/ \
--input-format CasavaOneEightSingleLanePerSampleDirFmt \
--output-path demux-single-end.qza
#ALTERNATIVE: import using manifest
qiime tools import \
  --type 'SampleData[SequencesWithQuality]' \
  --input-path manifest.tsv \
  --output-path demux-single-end.qza \
  --input-format SingleEndFastqManifestPhred33V2
#summarize
qiime demux summarize \
--i-data demux-single-end.qza \
--o-visualization demux.qzv

#dada2 cleanup
qiime dada2 denoise-single \
--i-demultiplexed-seqs demux-single-end.qza \
--p-n-threads 16 \
--p-trim-left 13 \
--p-trunc-len 181 \
--o-representative-sequences unfiltered-rep-seqs.qza \
--o-table unfiltered-table.qza \
--o-denoising-stats unfilter-denoise-stats.qza
##LONG; several hours
#tabulate results of dada2
qiime metadata tabulate \
--m-input-file unfilter-denoise-stats.qza \
--o-visualization unfilter-denoise-stats.qzv

#filter low-depth seqs
qiime feature-table filter-samples \
--i-table unfiltered-table.qza \
--p-min-frequency 1500 \
--o-filtered-table filtered-table.qza

qiime feature-table filter-seqs \
--i-data unfiltered-rep-seqs.qza \
--i-table filtered-table.qza \
--o-filtered-data filtered-rep-seqs.qza
#summarize results
qiime feature-table summarize \
--i-table filtered-table.qza \
--m-sample-metadata-file metadata.tsv \
--o-visualization filtered-table.qzv
qiime feature-table tabulate-seqs \
--i-data filtered-rep-seqs.qza \
--o-visualization filtered-rep-seqs.qzv

#optional: create new folders for visualizations and unfiltered

#taxonomy classification
qiime feature-classifier classify-sklearn \
--i-classifier silva-classifier.qza \
--i-reads filtered-rep-seqs.qza \
--o-classification taxonomy.qza
##LONG; overnight
#view results
qiime metadata tabulate \
--m-input-file taxonomy.qza \
--o-visualization taxonomy.qzv

#taxa barplots
qiime taxa barplot \
--i-table filtered-table.qza \
--i-taxonomy taxonomy.qza \
--m-metadata-file metadata.tsv \
--o-visualization taxa-bar-plots.qzv
#can get taxonomy tables from this.. or the following
qiime taxa collapse \
--i-table filtered-table.qza \
--i-taxonomy taxonomy-silva.qza \
--p-level 8 \
--o-collapsed-table lvl8_collapsed_taxa-bar-plots-silva.qza

##alpha and beta diversity stats
qiime phylogeny align-to-tree-mafft-fasttree \
--i-sequences rep-seqs.qza \
--o-alignment aligned-rep-seqs.qza \
--o-masked-alignment masked-aligned-rep-seqs.qza \
--o-tree unrooted-tree.qza \
--o-rooted-tree rooted-tree.qza
#then generate diversity core metrics
qiime diversity core-metrics-phylogenetic \
--i-phylogeny rooted-tree.qza \
--i-table filtered-table.qza \
--p-sampling-depth 1000 \
--m-metadata-file metadata.tsv \
--output-dir core_metrics_results
