#!/usr/bin/tcsh

#Downloaded Silva release 138 in August 2021 - fasta files of database and taxonomy file

#138.1-SSURef-trunc.fasta - seqs
#aligned and truncated (unaligned regions cut out)

#importing sequences
qiime tools import \
--type 'FeatureData[AlignedSequence]' \
--input-path SILVA138.fasta \
--input-format AlignedRNAFASTAFormat \
--output-path silva_138.qza
##translates into DNA since silva is RNA formatted
#importing Silva taxonomy
qiime tools import \
--type 'FeatureTable[Taxonomy]' \
--input-format HeaderlessTSVTaxonomyFormat \
--input-path tax_silva_138.txt \
--output-path silva-138-taxonomy.qza

#trimmed the database reads by 515F/806R primers
qiime feature-classifier extract-reads \
--i-sequences silva_138.qza \
--p-f-primer GTGCCAGCMGCCGCGGTAA \
--p-r-primer GGACTACHVGGGTWTCTAAT \
--p-trunc-len 120 \
--p-min-length 100 \
--p-max-length 400 \
--o-reads silva-138-ref-seqs.qza

#then trained the Qiime classifier on this database
qiime feature-classifier fit-classifier-naive-bayes \
--i-reference-reads silva-138-ref-seqs.qza \
--i-reference-taxonomy silva-138-taxonomy.qza \
--o-classifier silva-138-classifier-qza
